create Database	customer_behavior;

use customer_behavior;

select * from customer limit 20;

-- Total Revenue generated by Male vs Female Customer --
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Which Customer used a Discount but still spent more than the Average purchase amount --
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Top 5 Products with the Highest Average Review Rating --
select item_purchased, round(AVG(review_rating), 2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Comparing the Average Purchase Amount between Standard and Express Shipping --
select shipping_type, round(AVG(purchase_amount), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Comparing the Average Spent and Total Revenue between Subscribers and Non-Subscriber --
select subscription_status,
Count(Customer_id) as total_customers,
round(AVG(purchase_amount), 2) as avg_spend,
round(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- 5 Prodcuts have the highest percentage of purchases with Discount Applied --
select item_purchased,
round(SUM(CASE when discount_applied = 'Yes' Then 1 else 0 end)/count(*) * 100, 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
